---
abstract: 'Amon2 authorization plugin'
author:
  - 'Nishibayashi Takuji <takuji31@gmail.com>'
build_requires:
  Test::LoadAllModules: 0.021
  Test::More: 0.98
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Web-Authorizer
provides:
  Amon2::Plugin::Web::Authorizer:
    file: lib/Amon2/Plugin/Web/Authorizer.pm
    version: 0
  Amon2::Web::Authorizer:
    file: lib/Amon2/Web/Authorizer.pm
    version: 0.01
  Amon2::Web::Authorizer::Config:
    file: lib/Amon2/Web/Authorizer/Config.pm
    version: 0
  Amon2::Web::Authorizer::Config::File:
    file: lib/Amon2/Web/Authorizer/Config/File.pm
    version: 0
  Amon2::Web::Authorizer::Config::List:
    file: lib/Amon2/Web/Authorizer/Config/List.pm
    version: 0
  Amon2::Web::Authorizer::Logical:
    file: lib/Amon2/Web/Authorizer/Logical.pm
    version: 0
  Amon2::Web::Authorizer::Session:
    file: lib/Amon2/Web/Authorizer/Session.pm
    version: 0
requires:
  Amon2: 3.00
  YAML::Syck: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
